- name: Installing stow on Arch Linux
  tags: stow

  handlers:
    - name: Stow dotfiles
      when: _dotfiles.changed
      shell: cd $HOME/.dotfiles && stow .

  block:
    - name: Installing stow
      community.general.pacman:
        name: stow 
        state: present
      become: true
    - name: Cloning .dotfiles
      register: _dotfiles 
      ansible.builtin.git:
        repo: 'https://github.com/aliasboink/.dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: main 
      notify: Stow dotfiles
