---
- name: Playbook_docker.yml - docker and stuff
  hosts: all
  become: true 

  tasks:
    - name: Install docker and docker compose and ctop
      pacman:
        update_cache: yes
        name:
          - docker
          - docker-compose
          - ctop

